/* SPDX-License-Identifier: GPL-2.0 */
#ifndef _ASM_X86_KVM_TYPES_H
#define _ASM_X86_KVM_TYPES_H

#define KVM_ARCH_NR_OBJS_PER_MEMORY_CACHE 8192
#define KVM_ARCH_NR_OBJS_PER_MEMORY_CACHE_MIN 4096

#endif /* _ASM_X86_KVM_TYPES_H */
